package de.matthiaseberlein.mp3lib;

public enum LanguageCode {
	yaa("Afar"),
	abk("Abkhazian"),
	ace("Achinese"),
	ach("Acoli"),
	ada("Adangme"),
	ady("Adyghe"),
	afr("Afrikaans"),
	ain("Ainu"),
	aka("Akan"),
	alb("Albanian"),
	ale("Aleut"),
	alt("Southern Altai"),
	amh("Amharic"),
	anp("Angika"),
	ara("Arabic"),
	arg("Aragonese"),
	arm("Armenian"),    //hye
	arn("Mapudungun / Mapuche"),
	arp("Arapaho"),
	arw("Arawak"),
	asm("Assamese"),
	ast("Asturian / Bable / Leonese / Asturleonese"),
	ava("Avaric"),
	awa("Awadhi"),
	aym("Aymara"),
	aze("Azerbaijani"),
	bak("Bashkir"),
	bal("Baluchi"),
	bam("Bambara"),
	ban("Balinese"),
	baq("Basque"),
	bas("Basa"),
	bej("Beja / Bedawiyet"),
	bel("Belarusian"),
	bem("Bemba"),
	ben("Bengali"),
	bho("Bhojpuri"),
	bik("Bikol"),
	bin("Bini / Edo"),
	bis("Bislama"),
	bla("Siksika"),
	bod("Tibetan (bod)"),
	bos("Bosnian"),
	bra("Braj"),
	bre("Breton"),
	bua("Buriat"),
	bug("Buginese"),
	bul("Bulgarian"),
	bur("Burmese (bur)"), //mya
	byn("Blin / Bilin"),
	cad("Caddo"),
	car("Calibi Carib"),
	cat("Catalan / Valencian"),
	ceb("Cebuano"),
	ces("Czech"),   //cze
	cha("Chamorro"),
	che("Chechen"),
	chi("Chinese"),
	chk("Chuukese"),
	chm("Mari"),
	chn("Chinook Jargon"),
	cho("Choctaw"),
	chp("Chipewyan / Dene Suline"),
	chr("Cherokee"),
	chv("Chuvash"),
	chy("Cheyenne"),
	cnr("Montenegrin"),
	cor("Cornish"),
	cos("Corcsican"),
	cre("Cree"),
	crh("Crimean Tatar/ Crimean Turkish"),
	csb("Kashubian"),
	cym("Welsh (cym)"),
	dak("Dakota"),
	dan("Danish"),
	dar("Dargwa"),
	del("Delaware"),
	den("Slave / Slave Athapascan"),
	deu("Deutsch"),
	dgr("Dogrib"),
	din("Dinka"),
	div("Divehi / Dhivehi / Maldivian"),
	doi("Dogri"),
	dsb("Lower Sorbian"),
	dua("Duala"),
	dut("Dutch"),
	dyu("Dyula"),
	dzo("Dzongkha"),
	efi("Efik"),
	eka("Ekajuk"),
	ell("Greek (ell)"),   //gre
	eng("English"),
	est("Estonian"),
	ewe("Ewe"),
	ewo("Ewondo"),
	fan("Fang"),
	fao("Faroese"),
	fas("Persian (fas)"),
	fat("Fanti"),
	fij("Fijian"),
	fil("Filipino / Pilipino"),
	fin("Finnish"),
	fon("Fon"),
	fra("Francais"),
	frr("Northern Frisian"),
	frs("Eastern Frisian"),
	fry("Western Frisian"),
	ful("Fulah"),
	fur("Friulian"),
	gaa("Ga"),
	gay("Gayo"),
	gba("Gbaya"),
	geo("Georgian"),    //kat
	gil("Gilbertese"),
	gla("Gaelic / Scottish Gaelic"),
	gle("Irish"),
	glg("Galician"),
	glv("Manx"),
	gon("Gondi"),
	gor("Gorontalo"),
	grb("Grebo"),
	grn("Guarani"),
	gsw("Swiss german / Alemannic / Alsatian"),
	guj("Gujarati"),
	gwi("Gwich In"),
	hai("Haida"),
	hat("Haitian / Haitian Creole"),
	hau("Hausa"),
	haw("Hawaiian"),
	heb("Hebrew"),
	her("Herero"),
	hil("Hiligaynon"),
	hin("Hindi"),
	hmn("Hmong / Mong"),
	hmo("Hiri Moto"),
	hrv("Croatian"),
	hsb("Upper Sorbian"),
	hun("Hungarian"),
	hup("Hupa"),
	iba("Iban"),
	ibo("Igbo"),
	ice("Icelandic"),   //isl
	iii("Sichuan Yi / Nuosu"),
	iku("Inuktitut"),
	ilo("Iloko"),
	ind("Indonesian"),
	inh("Ingush"),
	ipk("Inupiag"),
	ita("Italian"),
	jav("Javanese"),
	jpn("Japanese"),
	jpr("Judeo Persian"),
	jrb("Judeo Arabic"),
	kaa("Kara Kalpac"),
	kab("Kabyle"),
	kac("Kachin / Jingpho"),
	kal("Kalaallisut / Greenlandic"),
	kam("Kamba"),
	kan("Kannada"),
	kas("Kashmiri"),
	kau("Kanuri"),
	kaz("Kazakh"),
	kbd("Kabardian"),
	kha("Khasi"),
	khm("Central Khamer"),
	kik("Kikuyu / Gikuyu"),
	kin("Kinyarwanda"),
	kir("Kirghiz / Kyrgyz"),
	kmb("Kimbundu"),
	kok("Konkani"),
	kom("Komi"),
	kon("Kongo"),
	kor("Korean"),
	kos("Kosraean"),
	kpe("Kpelle"),
	krc("Karachay Balkar"),
	krl("Karelian"),
	kru("Kurukh"),
	kua("Kuanyama / Kwanyama"),
	kum("Kumyk"),
	kur("Kurdish"),
	kut("Kutenai"),
	lad("Ladino"),
	lah("Lahnda"),
	lam("Lamba"),
	lao("Lao"),
	lav("Latvian"),
	lez("Lezghian"),
	lim("Limburgan / Limburger / Limburgish"),
	lin("Lingala"),
	lit("Lithuanian"),
	lol("Mongo"),
	loz("Lozi"),
	ltz("Luxembourgish / Letzeburgesch"),
	lua("Luba Lubua"),
	lub("Luba Katanga"),
	lug("Ganda"),
	lun("Lunda"),
	luo("Luo"),
	lus("Lushai"),
	mac("Macedonian"),  //mkd
	mad("Madurese"),
	mag("Magahi"),
	mah("Mashallese"),
	mai("Maithili"),
	mak("Makasar"),
	mal("Malayalam"),   //msa
	man("Maningo"),
	mao("Maori"),   //mri
	mar("Marathi"),
	mas("Masai"),
	may("Malay"),
	mdf("Makosha"),
	mdr("Mandar"),
	men("Mende"),
	mic("Mi Kmaq / Micmac"),
	min("Minangkabau"),
	mlg("Malagasy"),
	mlt("Maltese"),
	mnc("Manchu"),
	mni("Manipuri"),
	moh("Mohawk"),
	mon("Mongolian"),
	mos("Mossi"),
	mus("Creek"),
	mwl("Mirandese"),
	mwr("Marwari"),
	myv("Erzya"),
	nap("Neapolitan"),
	nau("Nauru"),
	nav("Navajo / Navaho"),
	nbl("South Ndebele"),
	nde("North Ndebele"),
	ndo("Ndonga"),
	nds("Sueddeutsch / Saechsisch / Low German / Low Saxon"),
	nep("Nepali"),
	New("Nepal Basa / Newari"),
	nia("Nias"),
	niu("Niuean"),
	nld("Flemish"),
	nno("Norwegian Nynorsk"),
	nob("Norwegian Bokmal"),
	nog("Nogai"),
	nor("Norwegian"),
	nqo("N Ko"),
	nso("Pedi / Sepedi / Northern Sotho"),
	nya("Chichewa / Chewa / Nyania"),
	nym("Nyamwezi"),
	nyn("Nyankole"),
	nyo("Nyoro"),
	nzi("Nzima"),
	oci("Occitan / Provencal"),
	oji("Ojibwa"),
	ori("Oriya"),
	oro("Oromo"),
	osa("Osage"),
	oss("Ossetian / Ossetic"),
	pag("Pangasinan"),
	pam("Pampanga / Kapampangan"),
	pan("Panjabi / Punjabi"),
	pap("Papiamento"),
	pau("Palauan"),
	per("Persian"),
	pol("Polish"),
	pon("Pohnpeian"),
	por("Portuguese"),
	pus("Pushto / Pashto"),
	que("Quechua"),
	raj("Rajasthani"),
	rap("Rapanui"),
	rar("Rarotongan / Cook Islands Maori"),
	roh("Romansh"),
	rom("Romany / Romanian"),
	rum("Moldavian"),
	ron("Moldovan"),
	run("Rundi"),
	rup("Aromanian / Arumanian / Macedo Romanian"),
	rus("Russian"),
	sad("Sandawe"),
	sag("Sango"),
	sah("Yakut"),
	sas("Sasak"),
	sat("Santali"),
	scn("Sicilian"),
	sco("Scots"),
	sel("Selkup"),
	shn("Shan"),
	sid("Sidamo"),
	sin("Sinhala / Sinhalese"),
	slk("Slovak (slk)"),
	slo("Slovak (slo)"),
	slv("Slovenian"),
	sma("Southern Sami"),
	sme("Northern Sami"),
	smj("Lule Sami"),
	smn("Inari Sami"),
	smo("Samoan"),
	sms("Skoli Sami"),
	sna("Shona"),
	snd("Sindhi"),
	snk("Soninke"),
	som("Somali"),
	sot("Sotho Southern"),
	spa("Spanish / Castilian"),
	sqi("Albanian (sqi)"),
	srd("Sardinian"),
	srn("Sranan Tongo"),
	srp("Serbian"),
	srr("Serer"),
	ssw("Swati"),
	suk("Sukuma"),
	sun("Sundanese"),
	sus("Susu"),
	swa("Swahili"),
	swe("Swedish"),
	syr("Syriac"),
	tah("Tahitian"),
	tam("Tamil"),
	tat("Tatar"),
	tel("Telugu"),
	tem("Timne"),
	ter("Tereno"),
	tet("Tetum"),
	tgk("Tajik"),
	tgl("Tagalog"),
	tha("Thai"),
	tib("Tibetan"),
	tig("Tigre"),
	tir("Tigrinya"),
	tiv("Tiv"),
	tkl("Tokelau"),
	tli("Tlingit"),
	tmh("Tamashek"),
	tog("Tonga Nyasa"),
	ton("Tonga Tongo Islands"),
	tpi("Tok Pisin"),
	tsi("Tsimshian"),
	tsn("Tswana"),
	tso("Tsonga"),
	tuk("Turkmen"),
	tum("Tumbuka"),
	tur("Turkish"),
	tvl("Tuvalu"),
	twi("Twi"),
	tyv("Tuvinian"),
	udm("Udmuri"),
	uig("Uighur"),
	ukr("Ukrainian"),
	umb("Umbundu"),
	urd("Urdu"),
	uzb("Uzbek"),
	vai("Vai"),
	ven("Venda"),
	vie("Vietnamese"),
	vot("Votic"),
	wal("Walamo"),
	war("Waray"),
	was("Washo"),
	wel("Welsh"),
	wln("Walloon"),
	wol("Wolof"),
	xal("Kalmyk / Oirat"),
	xho("Xhosa"),
	yao("Yao"),
	yap("Yapese"),
	yid("Yiddish"),
	yor("Yoruba"),
	zap("Zapotec"),
	zen("Zenaga"),
	zgh("Standard Moroccan Tamazight"),
	zha("Zhuang / Chuang"),
	zho("Chinese (zho)"),
	zul("Zulu"),
	zun("Zuni"),
	zza("Zaza / Dimili / Dimli / Kirdki / Kirmanjki / Zazaki");
	
	
	private String value;
	
	LanguageCode(String value) {
		this.value=value;
	}
	
	public String getValue() {
		return value;
	}
	
	public static LanguageCode getLanguageCodeByValue(String value){
		LanguageCode[] codes= LanguageCode.values();
		for(LanguageCode code : codes) {
			if(code.value.contains(value)){
				return code;
			}
		}
		return null;
	}
}
